name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew

      - name: Build fat JAR
        run: ./gradlew shadowJar

      - name: Copiar JAR a EC2
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: build/libs/spBack-1.0-all.jar
          target: /home/ubuntu/spBack/

      - name: Reiniciar servicio en EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl restart spback